
export const DEPLOYMENT_ADD_CLICKED = 'DAC';
export const DEPLOYMENT_ADD_BRANCH_NAME_CHANGE = 'DABNC';
export const DEPLOYMENT_ADD_PUBLIC_URL_CHANGE = 'DAPUC';
export const DEPLOYMENT_ADD_ENVIRONMENT_CHANGE = 'DAEC';

export const DEPLOYMENT_ADD_CANCEL = 'DACC';
export const DEPLOYMENT_NEW = 'DN';
export const DEPLOYMENT_SAVE_STARTED = 'DSS';
export const DEPLOYMENT_SAVE_FAILED = 'DSF';