image: mcr.microsoft.com/dotnet/core/sdk:3.0

stages:
    - build
    - publish-artifacts

server-build:
    stage: build
    before_script:
    - dotnet tool restore
    script:
    - dotnet build
    - dotnet dotnet-ef database update --project DeploymentTrackerCore
    - mv DeploymentTrackerCore/deployment.db .
    - dotnet dotnet-ef migrations script -o database-upgrade.sql --project DeploymentTrackerCore
    artifacts:
        name: server-database
        paths:
        - deployment.db
        - database-upgrade.sql

client-build:
    stage: build
    image: node
    before_script:
    - cd DeploymentTrackerCore/Frontend
    - npm ci
    script:
    - npm run build-production
    artifacts:
        name: frontend-resources
        paths:
        - DeploymentTrackerCore/wwwroot

linux-publish:
    stage: publish-artifacts
    dependencies:
    - client-build
    - server-build
    script:
    - dotnet publish DeploymentTrackerCore -c Release -r linux-x64 -o deployment-tracker/
    - cp deployment.db deployment-tracker/
    - cp database-upgrade.sql deployment-tracker/
    - mv deployment-tracker/DeploymentTrackerCore deployment-tracker/deployment-tracker
    artifacts:
        name: deployment-tracker-linux-x64
        paths:
        - deployment-tracker/
        expire_in: 1 week

windows-publish:
    stage: publish-artifacts
    dependencies:
    - client-build
    - server-build
    script:
    - dotnet publish DeploymentTrackerCore -c Release -r win-x64 -o deployment-tracker/
    - cp deployment.db deployment-tracker/
    - mv deployment-tracker/DeploymentTrackerCore deployment-tracker/deployment-tracker
    artifacts:
        name: deployment-tracker-windows-x64
        paths:
        - deployment-tracker/
        expire_in: 1 week
