image: mcr.microsoft.com/dotnet/core/sdk:2.2

stages:
    - build
    - publish-artifacts

server-build:
    stage: build
    before_script:
    - dotnet tool install -g --version 2.2.4 dotnet-ef
    script:
    - dotnet build
    - dotnet ef database update
    - dotnet ef migrations script -o database-upgrade.sql
    artifacts:
        name: server-database
        paths:
        - deployment.db
        - database-upgrade.sql

client-build:
    stage: build
    image: node
    before_script:
    - cd Frontend
    - npm ci
    script:
    - npm run build-production
    artifacts:
        name: frontend-resources
        paths:
        - wwwroot

linux-publish:
    stage: publish-artifacts
    dependencies:
    - client-build
    - server-build
    script:
    - dotnet publish -c Release -r linux-x64 -o deployment-tracker/
    - cp deployment.db deployment-tracker/
    - cp database-upgrade.sql deployment-tracker/
    artifacts:
        name: deployment-tracker-linux-x64
        paths:
        - deployment-tracker/
        expire_in: 1 week

windows-publish:
    stage: publish-artifacts
    dependencies:
    - client-build
    - server-build
    script:
    - dotnet publish -c Release -r win-x64 -o deployment-tracker/
    - cp deployment.db deployment-tracker/
    artifacts:
        name: deployment-tracker-windows-x64
        paths:
        - deployment-tracker/
        expire_in: 1 week