// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using deployment_tracker.Models;

namespace deployment_tracker.Migrations
{
    [DbContext(typeof(DeploymentAppContext))]
    [Migration("20190425084400_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("deployment_tracker.Models.Deployment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BranchName");

                    b.Property<int?>("DeployedEnvironmentId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("DeployedEnvironmentId");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("deployment_tracker.Models.Environment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("deployment_tracker.Models.Deployment", b =>
                {
                    b.HasOne("deployment_tracker.Models.Environment", "DeployedEnvironment")
                        .WithMany("Deployments")
                        .HasForeignKey("DeployedEnvironmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
