export const DEPLOYMENT_ADD_CLICKED = 'DAC';
export const DEPLOYMENT_ADD_BRANCH_NAME_CHANGE = 'DABNC';
export const DEPLOYMENT_ADD_SITE_NAME_CHANGE = 'DASNC';
export const DEPLOYMENT_ADD_PUBLIC_URL_CHANGE = 'DAPUC';
export const DEPLOYMENT_ADD_ENVIRONMENT_CHANGE = 'DAEC';

export const DEPLOYMENT_ADD_CANCEL = 'DACC';
export const DEPLOYMENT_NEW = 'DN';
export const DEPLOYMENT_SAVE_STARTED = 'DSS';
export const DEPLOYMENT_SAVE_FAILED = 'DSF';

export const DEPLOYMENT_SEARCH = 'DSRCH';
export const DEPLOYMENT_STATUS_FILTER_CHANGE = 'DSFC';
export const DEPLOYMENT_TYPE_FILTER_CHANGE = 'DTFS';
export const DEPLOYMENT_ONLY_MINE_FILTER_CHANGE = 'DOMFC';

export const JIRA_STATUS_UPDATE = 'JSU';
