// <auto-generated />
using System;
using DeploymentTrackerCore.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeploymentTrackerCore.Migrations
{
    [DbContext(typeof(DeploymentAppContext))]
    [Migration("20210308045700_Deployment-properties")]
    partial class Deploymentproperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("DeploymentTrackerCore.Models.Entities.Deployment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeployedEnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeploymentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicURL")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeployedEnvironmentId");

                    b.HasIndex("TypeId");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("DeploymentTrackerCore.Models.Entities.DeploymentEnvironment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("DeploymentTrackerCore.Models.Entities.DeploymentNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeploymentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.ToTable("DeploymentNote");
                });

            modelBuilder.Entity("DeploymentTrackerCore.Models.Entities.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeploymentTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TeardownTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("DeploymentTrackerCore.Models.Entities.UserEntityLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferencedEntity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TargetUserName");

                    b.ToTable("UserEntityLinks");
                });

            modelBuilder.Entity("DeploymentTrackerCore.Models.Entities.Deployment", b =>
                {
                    b.HasOne("DeploymentTrackerCore.Models.Entities.DeploymentEnvironment", "DeployedEnvironment")
                        .WithMany("Deployments")
                        .HasForeignKey("DeployedEnvironmentId");

                    b.HasOne("DeploymentTrackerCore.Models.Entities.Type", "Type")
                        .WithMany("Deployments")
                        .HasForeignKey("TypeId");

                    b.OwnsOne("DeploymentTrackerCore.Models.Entities.AuditDetail", "CreatedBy", b1 =>
                        {
                            b1.Property<int>("DeploymentId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("DeploymentId");

                            b1.ToTable("Deployments");

                            b1.WithOwner()
                                .HasForeignKey("DeploymentId");
                        });

                    b.OwnsOne("DeploymentTrackerCore.Models.Entities.AuditDetail", "ModifiedBy", b1 =>
                        {
                            b1.Property<int>("DeploymentId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("DeploymentId");

                            b1.ToTable("Deployments");

                            b1.WithOwner()
                                .HasForeignKey("DeploymentId");
                        });

                    b.OwnsOne("DeploymentTrackerCore.Models.Entities.Login", "SiteLogin", b1 =>
                        {
                            b1.Property<int>("DeploymentId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Password")
                                .HasColumnType("TEXT");

                            b1.Property<string>("UserName")
                                .HasColumnType("TEXT");

                            b1.HasKey("DeploymentId");

                            b1.ToTable("Deployments");

                            b1.WithOwner()
                                .HasForeignKey("DeploymentId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("DeployedEnvironment");

                    b.Navigation("ModifiedBy")
                        .IsRequired();

                    b.Navigation("SiteLogin");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DeploymentTrackerCore.Models.Entities.DeploymentNote", b =>
                {
                    b.HasOne("DeploymentTrackerCore.Models.Entities.Deployment", "Deployment")
                        .WithMany("DeploymentNotes")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DeploymentTrackerCore.Models.Entities.AuditDetail", "CreatedBy", b1 =>
                        {
                            b1.Property<int>("DeploymentNoteId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("DeploymentNoteId");

                            b1.ToTable("DeploymentNote");

                            b1.WithOwner()
                                .HasForeignKey("DeploymentNoteId");
                        });

                    b.OwnsOne("DeploymentTrackerCore.Models.Entities.AuditDetail", "ModifiedBy", b1 =>
                        {
                            b1.Property<int>("DeploymentNoteId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("DeploymentNoteId");

                            b1.ToTable("DeploymentNote");

                            b1.WithOwner()
                                .HasForeignKey("DeploymentNoteId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("Deployment");

                    b.Navigation("ModifiedBy")
                        .IsRequired();
                });

            modelBuilder.Entity("DeploymentTrackerCore.Models.Entities.UserEntityLink", b =>
                {
                    b.OwnsOne("DeploymentTrackerCore.Models.Entities.AuditDetail", "CreatedBy", b1 =>
                        {
                            b1.Property<int>("UserEntityLinkId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("UserEntityLinkId");

                            b1.ToTable("UserEntityLinks");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityLinkId");
                        });

                    b.OwnsOne("DeploymentTrackerCore.Models.Entities.AuditDetail", "ModifiedBy", b1 =>
                        {
                            b1.Property<int>("UserEntityLinkId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("UserEntityLinkId");

                            b1.ToTable("UserEntityLinks");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityLinkId");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("DeploymentTrackerCore.Models.Entities.Deployment", b =>
                {
                    b.Navigation("DeploymentNotes");
                });

            modelBuilder.Entity("DeploymentTrackerCore.Models.Entities.DeploymentEnvironment", b =>
                {
                    b.Navigation("Deployments");
                });

            modelBuilder.Entity("DeploymentTrackerCore.Models.Entities.Type", b =>
                {
                    b.Navigation("Deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
